title: 'Bushwick Ayuda Mutua'
email: info@nicholasfrota.com
description: >- # this means to ignore newlines until "baseurl:"
  Lorem Ipsum
baseurl: 'bushwichayudamutua.com'
basecolor: '#000000' # for browser settings
url: 'bushwichayudamutua.com'
img: 'BAM.svg'
twitter_username: 
github_username: 

plugins:
  - airtable
  - jekyll-admin

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
