title: Bushwick Ayuda Mutua
email: info@nicholasfrota.com
description: >- # this means to ignore newlines until "baseurl:"
  Lorem Ipsum
baseurl: ''
basecolor: '#000000' # for browser settings
url: ''
twitter_username: 
github_username: 

plugins:
  - airtable
  - jekyll-admin

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
theme: jekyll-theme-cayman